name: Update TAC data from LFX
description: Action that syncs data from LFX into the TAC website
inputs:
  landscape_url:
    description: "URL for the project's landscape"
    default: ""
  artwork_url:
    description: "URL for the project's artwork repo"
    default: ""
  lfx_tac_committee_url:
    description: "URL to the committee in LFX"
    default: ""
  tac_agenda_gh_project_url:
    description: "URL for the GitHub Project in the TAC repo for managing TAC meeting agendas"
    default: ""
runs:
  using: composite
  steps:
  - name: Harden Runner
    uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
    with:
      egress-policy: audit
  - name: Check out repo
    uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    with:
      token: ${{ env.token }}
      repository: ${{ env.repository }}
      ref: ${{ env.ref }}
      path: tac-repo
  - name: Checkout lfx-tac-actions
    uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7@v4
    with:
      token: ${{ env.token }}
      repository: jmertic/lfx-tac-actions
      path: lfx-tac-actions
  - name: Set up Python 3.x
    uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
    with:
      python-version: '3.x'
  - name: Run build
    working-directory: ./tac-repo
    shell: bash
    env:
      LANDSCAPE_URL: ${{ inputs.landscape_url }}
      ARTWORK_URL: ${{ inputs.artwork_url }}
      LFX_TAC_COMMITTEE_URL: ${{ inputs.lfx_tac_committee_url }}
      TAC_AGENDA_GH_PROJECT_URL: ${{ inputs.tac_agenda_gh_project_url }}
      GH_TOKEN: ${{ env.token }}
      GITHUB_TOKEN: ${{ env.token }}
    run: |
      python ../lfx-tac-actions/updateprojects.py
      python ../lfx-tac-actions/updatetacmembers.py
      python ../lfx-tac-actions/updatetacagendaitems.py
  - name: Get current date
    id: date
    uses: Kaven-Universe/github-action-current-date-time@f2c12d90cff9c3e7b1f50430886e632fe31fcee1 # v1.4.0
    with:
      format: "YYYY-MM-DD"
  - name: Create Pull Request
    uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
    with:
      token: ${{ env.token }}
      branch-suffix: timestamp
      path: ./tac-repo
      title: "Update Data Sources from LFX ${{ steps.date.outputs.time }}"
      labels: automerge
      commit-message: Update Data Sources from LFX
      signoff: true


